Durable state store.
akka/akka-persistence-spanner pull request #145
Opened 2021-07-29 15:10 UTC by RayRoestenburg

Durable state store.

2021-07-29 15:11 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/SpannerObjectStore.scala
> +      timestamp: Long
Added timestamp, so SpannerDurableStateStore can use it, probably a breaking change for existing users.

2021-07-29 15:11 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
> +          timestamp = SpannerUtils.spannerTimestampToUnixMillis(obj.writeTime)
Added timestamp.

2021-07-29 15:39 UTC, debasishg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +}
should we think of a serialization class where this can be refactored into ? We have  a similar `AkkaSerialization` class in JDBC plugin ..

2021-07-29 15:59 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +}
Different projects, I would prefer we don't do that.

2021-07-29 16:27 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +        tag, // tag is used as entityType in spanner store
I assumed this, please check. (tag == entityType)

2021-07-29 16:27 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +    // tag == entityType in spanner store
assumption.

2021-07-29 16:27 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +    // tag == entityType in spanner store
assumption.

2021-07-29 20:02 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +        tag, // tag is used as entityType in spanner store
This assumption allows me to completely reuse SpannerObjectStore, if this is not wanted, I guess we will have to add another table definition specifically with a "tag" column in it, or possibly, add a tag column? The issue with that would be that you can't always extract entity out of persistenceId string.. help please.

2021-07-30 04:24 UTC, debasishg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +}
I am not talking about reusing. Maybe we can factor out the serialization bits into a similar class here named `AkkaSerialization`

2021-07-30 07:11 UTC, debasishg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +                deserialize(r.byteString.toArray, r.serId.asInstanceOf[Int], r.serManifest)
Is `r.serId` a Long ? Then we can use `r.serId.toInt` instead of the cast.

2021-07-30 07:12 UTC, debasishg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +      value = deserialize(change.bytes.toArray, change.serId.asInstanceOf[Int], change.serManifest).get, // crash source if corrupt.
same as before `r.serId.toInt` instead of the cast ?

2021-07-30 07:13 UTC, debasishg commented on journal/src/test/scala/akka/persistence/spanner/SpannerDurableStateStoreSpec.scala
> +  override def withObjectStore: Boolean = true
can't we make this a `val` ?

2021-07-30 10:34 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +}
oh ok, got it. Everything is already in two small methods, `serialize` and `deserialize`, should be ok

2021-07-30 10:35 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +        tag, // tag is used as entityType in spanner store
So instead, I'm going to add a `tag` column in the table, and always fill `entityType` with empty string. I'll add a ticket for further improvement. There are likely follow up discussions around `PersistenceId`.

2021-07-30 10:36 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +                deserialize(r.byteString.toArray, r.serId.asInstanceOf[Int], r.serManifest)
Of course! argh

2021-07-30 10:37 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +      value = deserialize(change.bytes.toArray, change.serId.asInstanceOf[Int], change.serManifest).get, // crash source if corrupt.
Don't rub it in please 😅

2021-07-30 10:39 UTC, RayRoestenburg commented on journal/src/test/scala/akka/persistence/spanner/SpannerDurableStateStoreSpec.scala
> +  override def withObjectStore: Boolean = true
yeah probably

2021-07-30 11:01 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
> +           |  tag STRING(MAX) NOT NULL
Added tag column so durable state store works, and SpannerObjectStore continues to work as is, though it does mean a table schema change. Expecting more improvements in this area (tagging, dynamic projections, etc).

2021-07-30 11:29 UTC, ignasi35 requested changes
upsertObject must pass the tag.

2021-07-30 11:29 UTC, ignasi35 commented on journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
> +           |  tag STRING(MAX) NOT NULL
Maybe it should be nullable? 🤔

2021-07-30 11:29 UTC, ignasi35 commented on journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
> +    upsertObject(entity, persistenceId, serId, serManifest, value, seqNr, "")
Oh, the empty tag is not `Null` but `""`.

2021-07-30 11:29 UTC, ignasi35 commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +        "", // cannot extract entityType from persistenceId.
Should this `upsertObject()` invocation set the tag? (use the new overload)

2021-07-30 11:31 UTC, ignasi35 approved these changes
I was reviewing commit by commit and noticed you already added the fix.

2021-07-30 11:31 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +        "", // cannot extract entityType from persistenceId.
I fixed it, yes, this sets the tag.

2021-07-30 11:32 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +          }
yes in this case it's not the best use of it ;-)

2021-07-30 11:33 UTC, ignasi35 commented
In other persistence plugins, when changing the schema we either document or provide the migration tools for users that already deployed the old schema.

We should have the `update` DML or docs alerting about the new column.

🤔 Hmm,  I guess it depends on when was the `state` table introduced in the schema.

2021-07-30 11:34 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +import akka.util.Timeout
why no warning in compile, are you sure?

2021-07-30 11:34 UTC, RayRoestenburg commented on journal/src/main/resources/reference.conf
>    }
same table.

2021-07-30 11:34 UTC, RayRoestenburg commented on journal/src/main/resources/reference.conf
>    }
I guess I can remove the `table=objects` in `durable-state-store`

2021-07-30 11:35 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
> +           |  tag STRING(MAX) NOT NULL
just adding in empty, the implementation of DurableStateStore expects it to exist.

2021-07-30 11:50 UTC, RayRoestenburg commented on journal/src/main/resources/reference.conf
>    }
Its actually a good point.. I have now added it tries to get the table first from durable-state-store, fallback to store.

2021-07-30 11:50 UTC, raboof commented
> In other persistence plugins, when changing the schema we either document or provide the migration tools for users that already deployed the old schema.
> 
> We should have the `update` DML or docs alerting about the new column.
> 
> thinking Hmm, I guess it depends on when was the `state` table introduced in the schema.

In this case we've never released a non-RC version with this table, so changing without docs. It might be nice to document it for akkaserverless' sake, though :)

2021-07-30 12:03 UTC, raboof commented on journal/src/main/resources/reference.conf
>    }
Perhaps we should remove `object` alltogether and put the options under `durable-state-store`? I don't see a reason to keep both.

2021-07-30 12:08 UTC, debasishg approved these changes
LGTM

2021-07-30 12:58 UTC, ignasi35 commented on docs/src/main/paradox/durable-state-store.md
> +There is no materialized view with a copy of the event so if an event that is tagged is deleted it will no longer show up in changes by tag queries.
```suggestion
There is no materialized view with a copy of the state so if a state that is tagged is deleted it will no longer show up in changes by tag queries.
```

Hmmm, this sounds dangerous. If I'm reading correctly, a projection may loose the last few changes of an entity:

```
...
entity123-rev6
entity123-rev7
entity123-rev8
entity123-rev9
(deleted)
```

If the projection lags behind and only consumes up to `entity123-rev7`, hard-deleting the entity at rev10 means the projection will not only miss rev8 and rev9, but also it'll miss the fact that the entity was deleted.

Is that alright? It looks like projections will become out of sync.

2021-07-30 12:58 UTC, ignasi35 commented on docs/src/main/paradox/durable-state-store.md
> +There is no materialized view with a copy of the event so if an event that is tagged is deleted it will no longer show up in changes by tag queries.
This problem is probably not exclusive to the spanner plugin, though. How do deletes work in the JDBC plugin and how does the JDBC plugin prevent this problem? cc @debasishg

2021-07-30 12:58 UTC, ignasi35 commented on journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
> +  val objectTable =
Is there a reason to not drop `object.table` yet?

2021-07-30 13:15 UTC, ignasi35 commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +import akka.util.Timeout
Maybe we haven't set up the disclipline plugin or the compiler settings. The IDE dropped a good chuck...

2021-07-30 13:18 UTC, RayRoestenburg commented on journal/src/main/resources/reference.conf
>    }
sure can do that.

2021-07-30 14:12 UTC, raboof commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +        "", // cannot extract entityType from persistenceId.
Instead of having both the `entityType` and the `tag`, perhaps we should just *replace* `entityType` with `tag`?

AFAIK the main reason for having `entityType` in Akka Serverless is so that we can then query for that entity in views - but that could work exactly the same by tagging all entities of a certain entity type with the same tag.

2021-07-30 14:15 UTC, raboof reviewed
In the end is it still useful to have both `SpannerObjectStore` and `scaladsl/SpannerDurableStateStore`? Eventually we'd want to port akkaserverless-framework to use the more public Durable State API's anyway. Perhaps keeping it for now might make porting easier, though

2021-07-30 14:21 UTC, RayRoestenburg commented
@raboof yes I'm leaving the existing one for now for compatibility, and there are still some issues / differences.

2021-07-30 14:22 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/SpannerSettings.scala
> +  val objectTable =
The existing API uses that (expects that) so it is likely more compatible like this now. I think it should be removed very soon, there will be a follow up issue.

2021-07-30 14:23 UTC, raboof commented
> there are still some issues / differences.

What are they? Should we resolve these before merging?

2021-07-30 14:23 UTC, RayRoestenburg commented on journal/src/main/scala/akka/persistence/spanner/state/scaladsl/SpannerDurableStateStore.scala
> +import akka.util.Timeout
ah discipline, is that a flag? maybe I forgot to run sbt with it if this is not automatically enabled...

2021-07-30 14:24 UTC, RayRoestenburg commented on journal/src/main/resources/reference.conf
>    }
Let's do that in follow up where we don't have the other implementation, since this config is probably used by existing apps.

2021-07-30 14:25 UTC, merged

2021-07-30 14:27 UTC, RayRoestenburg commented
@raboof there is a wider conversation probably to be had about `PersistenceId`, entityType / Hint, being able to extract this or not, supporting only persistence typed or not, but this conversation is probably best done when some are back from holiday. I'll add a placeholder for now.

2021-08-09 14:27 UTC, patriknw reviewed
We should try this out before releasing next version. I suspect several thing in the implementation can be simplified. SpannerDurableStateStore and SpannerObjectStore can probably be collapsed.

2021-08-09 14:27 UTC, patriknw commented on journal/src/main/scala/akka/persistence/spanner/internal/SpannerObjectInteractions.scala
> +           |  tag STRING(MAX) NOT NULL
Ouch, in Akka Serverless there is no slices/tags yet so this is in the `entity_type` column. That was rather stupid of us to not add the tag column up front. This will be some migration work now.